#!/usr/bin/env python

import argparse
import hashlib
from pathlib import Path
import os
import subprocess
import zlib
import sys

def read_blob(filename):
    with open(filename, 'br') as fh:
        return zlib.decompress(fh.read())

class Commit():

    metadata = None
    annotation = None
    message = None

    def length(self):
        if self.annotation is not None:
            return len(self.metadata) + 1 + len(self.annotation) + 2 + len(self.message)
        else:
            return len(self.metadata) + 2 + len(self.message)

    def top(self):
        return b'commit %a\x00' % self.length()

    def sha(self):
        m = hashlib.sha1()
        m.update(self.bytes())

        return m.hexdigest()

    def bytes(self):
        bs = self.top()
        bs += self.metadata
        bs += b'\n'

        if self.annotation is not None:
            bs += self.annotation
            bs += b'\n'

        bs += b'\n'
        bs += self.message

        return bs

    def zip(self):
        return zlib.compress(self.bytes())

    def path(self, top_level=None):
        sha = self.sha()

        relative = '.git/objects/' + sha[0:2] + '/' + sha[2:]

        if top_level:
            return Path(top_level + '/' + relative)
        else:
            return Path(relative)

    def __init__(self, metadata, message, annotation=None):
        self.metadata = metadata
        self.annotation = annotation
        self.message = message

    @staticmethod
    def from_blob(blob):
        self = Commit('', '')
        a = 0
        b = 0
        while blob[b] != 0:
            b += 1
        b += 1
        a = b

        while blob[b] != ord('\n') or blob[b+1] != ord('\n'):
            b += 1
        self.metadata = blob[a:b]

        b += 2
        self.message = blob[b:]

        b = len(self.metadata)
        while self.metadata[b-1] != ord('\n'):
            b -= 1

        annotation = self.metadata[b:].decode('utf-8')
        if not any([
                annotation.startswith('committer'),
                annotation.startswith('author'),
                annotation.startswith('parent'),
                annotation.startswith('tree'),
            ]):
            self.annotation = self.metadata[b:]
            self.metadata = self.metadata[0:b-1]

        return self


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Annotate git commit objects.',
        epilog=(
            'The "annotate" and "remove" options are mutually exclusive.'
            ' '
            'Only HEAD can be annotated.'
        ),
    )
    parser.add_argument(
        '-a', '--annotate', help='Annotate commit object with message',
        metavar='ANNOTATION',
    )
    parser.add_argument(
        '-r', '--remove', help='Remove annotation from commit object', action='store_true',
    )
    args = parser.parse_args()

    if args.annotate and args.remove:
        parser.print_help()
        sys.exit(1)

    head = subprocess.check_output('git rev-parse HEAD', shell=True, encoding='UTF-8')
    head = head[0 : len(head)-1]
    filename = '.git/objects/' + head[0:2] + '/' + head[2:]

    top_level = subprocess.check_output('git rev-parse --show-toplevel', shell=True, encoding='UTF-8')
    top_level = top_level[0 : len(top_level)-1]

    blob = read_blob(top_level + '/' + filename)
    old_commit = Commit.from_blob(blob)

    if args.remove and old_commit.annotation is None:
        sys.exit(0)

    new_commit = Commit(old_commit.metadata, old_commit.message)
    if args.annotate:
        new_commit.annotation = args.annotate.encode('utf-8')
    else:
        new_commit.annotation = None

    new_commit.path(top_level).parent.mkdir(parents=True, exist_ok=True)

    with new_commit.path(top_level).open('wb') as fh:
        fh.write(new_commit.zip())
        old_commit.path(top_level).unlink()
        os.system('grep -rl {} {} | xargs sed -i "s/{}/{}/g" > /dev/null'.format(old_commit.sha(), top_level, old_commit.sha(), new_commit.sha()))
